# Generated by Django 3.0.2 on 2020-06-09 17:51

from django.db import migrations, models
import restapi.models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0002_auto_20200609_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=restapi.models.upload_status_image),
        ),
    ]
